### ISSUE TITLE
Is it supposed to look like this?

### ISSUE THREAD

**Issue by nco2k** [DaFuqs/FluidVoidFading#12]
![lava](https://github.com/DaFuqs/FluidVoidFading/assets/26080123/f59ff31b-18ce-4378-9bae-ba086818b6d6)

- Fluid Void Fading 1.1.5
- Fabric API 0.97.1+1.20.4
- Sodium mc1.20.4-0.5.8
- Cloth Config API 13.0.121+fabric

**Comment by DaFuqs** [comment]
Does it look the same without Sodium?

**Comment by nco2k** [comment]
this is how it looks like without sodium:

![lava](https://github.com/DaFuqs/FluidVoidFading/assets/26080123/f7bba0ba-50e5-4b09-90c4-1c7488c381d3)

**Comment by DaFuqs** [comment]
I tried for 2 days and still do not know how to handle the sodium part since I do not understand their code.
This is something I cannot solve myself for the time being.

**Comment by DaFuqs** [comment]
Fixed for Sodium 0.6.x and released as v1.1.6
