### ISSUE TITLE
Doesn't work with Sodium

### ISSUE THREAD

**Issue by noblereign** [DaFuqs/FluidVoidFading#2]
title says it all really
tested with 1.19.2
![saltless](https://user-images.githubusercontent.com/2935979/216888254-a6efc8d0-e665-4296-8341-bf2d0effcf0f.png)

**Comment by Aces-and-Jacks** [comment]
Sodium Compatibility is released so this can be closed now 🎊 🎆

**Comment by DaFuqs** [comment]
Indeed, ty! 👌
