### ISSUE TITLE
why

### ISSUE THREAD

**Issue by S34Ka** [DaFuqs/FluidVoidFading#3]
Why optimization?

**Comment by DaFuqs** [comment]
What is the question exactly?

**Comment by S34Ka** [comment]
> В чем именно заключается вопрос?

I have a weak laptop, so I often visit the optimization tab, during one of my visits, I noticed your mod there, but I don't fully understand exactly how it affects the optimization of the game

**Comment by DaFuqs** [comment]
Oh, you are wondering why the mod is flagged as optimization on Modrinth.
It improves rendering. Since Modrinth does not have a visuals category I put it there. But I don't care, really, will remove that flag.
