### ISSUE TITLE
Liquid isn't fading into the void, instead being a fade dark

### ISSUE THREAD

**Issue by Scarlaid** [DaFuqs/FluidVoidFading#5]
![image](https://github.com/DaFuqs/FluidVoidFading/assets/90851437/3993599b-f76b-4e65-86ae-c4766188d721)

if this mod is only available to vanilla texture, I will close the issue.

**Comment by DaFuqs** [comment]
Should work with all fluids.
Is that 1.19.4? Any other mods?

**Comment by Scarlaid** [comment]
This is 1.19.4 while using the 1,19,3 version of the mod 
I do have BedrockWater mod atm for immersive underwater fog, might be?

**Comment by Scarlaid** [comment]
nope wasnt it sadly
![image](https://github.com/DaFuqs/FluidVoidFading/assets/90851437/1659c025-c80c-403c-bdc6-2e6b2c671619)

my log: https://mclo.gs/Z8Y0leO
my mods: [installed-mods.txt](https://github.com/DaFuqs/FluidVoidFading/files/11930130/installed-mods.txt)

**Comment by DaFuqs** [comment]
The version for 1.19.3 nicely for me on 1.19.4. I've flagged it as such on Curseforge and Modrinth now. (both with and without sodium)

Should you find out what combination of mods causes the render bug I'll be able to look into it ✅

**Comment by Scarlaid** [comment]
Took 30 mins, but I found it.
It was [Nvidum](https://modrinth.com/mod/nvidium) causing the incompatibility
###### not surprise because it cant even run with Iris

![image](https://github.com/DaFuqs/FluidVoidFading/assets/90851437/baf41433-0ad5-42f3-b8f0-4c4659c40285)

**Comment by DaFuqs** [comment]
Oh, well this is awkward. I don't even have a nvidia card to debug this. Oof.
Guess I'll just mark nvidum as incompatible?

**Comment by Scarlaid** [comment]
yeah, you should for the time being, until someone can help

**Comment by DaFuqs** [comment]
Sadly a mod compat issue I cannot fix on my end.
