### ISSUE TITLE
Add support for Sodium 0.5 / Iris 1.6.5

### ISSUE THREAD

**Issue by ShrikerChestTree** [DaFuqs/FluidVoidFading#7]
There was found a bug about incompatibility with Sodium 0.5 and Iris 1.6.5 please try to fix it in the new version!
Minecraft 1.20.1
Fabric API 0.86.1
Fluid Void Fading 1.1.0

**Comment by LokeYourC3PH** [comment]
Came here to say this. There's like three mods currently causing this for me: Cauldron Dyeing, Fluid Void Fading and Cull Leaves.

**Comment by DaFuqs** [comment]
Duplicate of #6. I'll look into that 👌
