### ISSUE TITLE
Remove quilt tag from modrinth versions

### ISSUE THREAD

**Issue by ItsProfessional** [DaFuqs/FluidVoidFading#9]
This mod doesn't natively support quilt, and works via quilt's fabric backwards compatibility.
As such, it should be tagged as fabric only, or, native support should be added.

**Comment by DaFuqs** [comment]
From an end users / quilt players perspective, 99% want to view all mods they can run in their quilt pack. That is, what those filters are for.

Implementation details shouldn't matter from most players perspective and the mod regularily get's tested to be working fine on quilt.

**Comment by ItsProfessional** [comment]
Okay. Can you add the quilt tag to all the releases then? The latest release is only tagged as fabric and that's causing issues with the ferium mod downloader

**Comment by DaFuqs** [comment]
Oh, that one definitely is on me. Wil do, ty!
